### ISSUE TITLE
maybe diamond error in PhaGCN 2.3

### ISSUE THREAD

**Issue by Songq-20** [KennthShang/PhaGCN2.0#17]
Hi, 
There're some errors when I try to use PhaGCN 2.3:
My commands:
```
mamba activate phagcn2
export MKL_SERVICE_FORCE_INTEL=1
cd PhaGCN2.0
python run_Speed_up.py --contigs contigs.fa --len 8000 
```
The errors :
```
/datanode03/songq/PhaGCN2.0/run_CNN.py:104: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  pretrained_dict=torch.load(args.classifier, map_location='cpu')
/datanode03/songq/PhaGCN2.0/run_CNN.py:114: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  tmp = torch.load(args.embed, map_location='cpu')
/data01nfs/user/songq/anaconda3/lib/python3.11/site-packages/Bio/Seq.py:2880: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(
  File "/data01nfs/user/songq/anaconda3/bin/diamond", line 113
    print "Diamond version %s" % (get_diamond_version())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
Traceback (most recent call last):
  File "/datanode03/songq/PhaGCN2.0/run_KnowledgeGraph.py", line 170, in <module>
    _ = make_diamond_db(64)
        ^^^^^^^^^^^^^^^^^^^
  File "/datanode03/songq/PhaGCN2.0/run_KnowledgeGraph.py", line 146, in make_diamond_db
    res = subprocess.run(make_diamond_cmd, check=True, stdout=subprocess.PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data01nfs/user/songq/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diamond', 'makedb', '--threads', '64', '--in', 'database/ALL_protein.fasta', '-d', 'database/database.dmnd']' returned non-zero exit status 1.
cat: result/pred/*: 没有那个文件或目录
```
It's  seems to be caused by incompatibility between the diamond version and the Python version. Diamond requires Python 2.x.
I install diamond by `pip install diamond`.
But another one install PhaGCN v2.2 , our python are all 3.x , and we install diamond by the same way. She can successfully run PhaGCN .
How can I solve this problem?
Thanks!

**Comment by xiahaolong** [comment]
Hello, please download the latest version of the run_Speed_up.py script. It has been tested and the issue has been fixed.

**Comment by yuanwenguang666** [comment]
Dear!

Sorry for the late reply.  Thank you for your feedback. After checking environment file , diamond is installed in our environment file. It may be because diamond was not fully installed when conda created the environment. If this problem occurs again, you just need to reinstall diamond and add it to your environment path.

All the best!
Wen-Guang

**Comment by Songq-20** [comment]
Hi,
Thanks for all reply, I solved it just by :
```
conda activate phagcn2
conda install python=2.7.18
```
And than it can run successfully.
I don't know if this command will have any other impact on PhaGCN2.3, but currently it seems to run successfully.
Best
Songqi

**Comment by yuanwenguang666** [comment]
There is no impact, please feel free to use.
